version: '3'
services:
  client:
    build:
      context: ./tay-tay-client
      dockerfile: Dockerfile
      target: production
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile.dev
#    ports:
#      - "8080:8080"
#    environment:
#    # Define environment variables for the backend service (development)
#    volumes:
#      - ./backend:/app
