version: '3'
services:
  client:
    build:
      context: ./tay-tay-client
      dockerfile: Dockerfile
      target: development
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "5173:5173"
    volumes:
      - ./tay-tay-client:/usr/src/app
      - /usr/src/app/node_modules
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile.dev
#    ports:
#      - "8080:8080"
#    environment:
#    # Define environment variables for the backend service (development)
#    volumes:
#      - ./backend:/app
