version: '3'
services:
  server:
    container_name: "tay-tay-server"
    build:
      context: ./tay-tay-server
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./tay-tay-server:/usr/src/app
    command: [ "./gradlew", "bootRun" ]
  client:
    container_name: "tay-tay-client"
    build:
      context: ./tay-tay-client
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./tay-tay-client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    command: ["npm", "run", "dev", "--", "--host"]
  proxy:
    container_name: "proxy"
    build: local-proxy
    restart: always
    ports:
      - "80:80"