services:
  database:
    image: postgres
    container_name: "tay-tay-database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tay-tay
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: "tay-tay-server"
    build:
      context: ./tay-tay-server
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./tay-tay-server:/usr/src/app
    command: [ "./gradlew", "bootRun" ]
    depends_on:
      database:
        condition: service_healthy

  client:
    container_name: "tay-tay-client"
    build:
      context: ./tay-tay-client
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./tay-tay-client:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_data: