name: Build image and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-image-and-push-to-ECR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load env
        run: cat "./production.env" >>$GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push Client image to Amazon ECR
        working-directory: ./tay-tay-client
        id: build-image
        env:
          CLIENT_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHA_TAG: ${{ github.sha }}
        run: |
          docker build -t $CLIENT_ECR_REGISTRY/$CLIENT_ECR_REPOSITORY:$SHA_TAG -t $ECR_REGISTRY/$CLIENT_ECR_REPOSITORY:latest .
          docker push $CLIENT_ECR_REGISTRY/$CLIENT_ECR_REPOSITORY:$SHA_TAG
          docker push $CLIENT_ECR_REGISTRY/$CLIENT_ECR_REPOSITORY:latest
