name: 🚀 Deploy Server and Client

on:
  workflow_dispatch:
    inputs:
      client_image_tag:
        description: 'CLIENT - Specify the Git SHA (default is "latest")'
        default: 'latest'
        required: false
      server_image_tag:
        description: 'SERVER - Specify the Git SHA (default is "latest")'
        default: 'latest'
        required: false

jobs:
  deploy-client:
    uses: ./.github/workflows/deploy_client.yml
    secrets: inherit
    with:
      image_tag: ${{ github.event.inputs.client_image_tag }}

  deploy-server:
    uses: ./.github/workflows/deploy_server.yml
    secrets: inherit
    with:
      image_tag: ${{ github.event.inputs.server_image_tag }}