name: PRODUCTION - Deploy Server

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify the Git SHA (default is "latest")'
        default: 'latest'
        required: false

env:
  AWS_REGION: eu-central-1
  AWS_CLIENT_CONTAINER_NAME: tay-tay-client-container
  AWS_CLIENT_ECS_TASK_DEFINITION_FAMILY: tay-tay-ecs-container-client
  AWS_CLIENT_ECS_SERVICE: tay-tay-ecs-service-client
  AWS_ECS_CLUSTER: tay-tay-ecs-cluster

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Client ECS Task
        uses: ./.github/workflows/deploy_ecs_task.yml
        with:
          ECS_CONTAINER_NAME: ${{ env.AWS_CLIENT_CONTAINER_NAME }}
          ECS_TASK_DEFINITION_FAMILY: ${{ env.AWS_CLIENT_ECS_TASK_DEFINITION_FAMILY }}
          ECS_SERVICE: ${{ env.AWS_CLIENT_ECS_SERVICE }}
          ECS_CLUSTER: ${{ env.AWS_ECS_CLUSTER }}
