name: PRODUCTION - Deploy Server

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify the Git SHA (default is "latest")'
        default: 'latest'
        required: false

env:
  AWS_REGION: eu-central-1
  AWS_SERVER_ECS_TASK_DEFINITION_FAMILY: tay-tay-ecs-task-server
  AWS_SERVER_CONTAINER_NAME: tay-tay-server-container
  AWS_SERVER_ECS_SERVICE: tay-tay-ecs-service-server
  AWS_ECS_CLUSTER: tay-tay-ecs-cluster
  AWS_SERVER_ECR_REPOSITORY: tay-tay-ecr-repository-server

jobs:
  deploy-server:
    uses: ./.github/workflows/deploy_task_definition_to_ECS.yml
    secrets: inherit
    with:
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ECS_TASK_DEFINITION_FAMILY: ${{ env.AWS_SERVER_ECS_TASK_DEFINITION_FAMILY }}
        AWS_CONTAINER_NAME: ${{ env.AWS_SERVER_CONTAINER_NAME }}
        AWS_ECS_SERVICE: ${{ env.AWS_SERVER_ECS_SERVICE }}
        AWS_ECS_CLUSTER: ${{ env.AWS_ECS_CLUSTER }}
        AWS_ECR_REPOSITORY: ${{ env.AWS_SERVER_ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.event.inputs.image_tag }}