name: 🚀 Deploy Client

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify the Git SHA (default is "latest")'
        default: 'latest'
        required: false

jobs:
  deploy-client:
    uses: ./.github/workflows/deploy_task_definition_to_ECS.yml
    secrets: inherit
    with:
      AWS_REGION: eu-central-1
      AWS_ECS_TASK_DEFINITION_FAMILY: tay-tay-ecs-task-client
      AWS_CONTAINER_NAME: tay-tay-client-container
      AWS_ECS_SERVICE: tay-tay-ecs-service-client
      AWS_ECS_CLUSTER: tay-tay-ecs-cluster
      AWS_ECR_REPOSITORY: tay-tay-ecr-repository-client
      IMAGE_TAG: ${{ github.event.inputs.image_tag }}