name: PRODUCTION - Deploy Client

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify the Git SHA (default is "latest")'
        default: 'latest'
        required: false

env:
  AWS_REGION: eu-central-1
  AWS_CLIENT_CONTAINER_NAME: tay-tay-client-container
  AWS_CLIENT_ECS_TASK_DEFINITION_FAMILY: tay-tay-ecs-container-client
  AWS_CLIENT_ECS_SERVICE: tay-tay-ecs-service-client
  AWS_ECS_CLUSTER: tay-tay-ecs-cluster

jobs:
  deploy-client:
    strategy:
      matrix:
        ecs_container_name: ${{ env.AWS_CLIENT_CONTAINER_NAME }}
        ecs_task_definition_family: ${{ env.AWS_CLIENT_ECS_TASK_DEFINITION_FAMILY }}
        ecs_service: ${{ env.AWS_CLIENT_ECS_SERVICE }}
        ecs_cluster: ${{ env.AWS_ECS_CLUSTER }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy Client ECS Task
        uses: ./.github/workflows/deploy.yml
        with:
          ECS_CONTAINER_NAME: ${{ matrix.ecs_container_name }}
          ECS_TASK_DEFINITION_FAMILY: ${{ matrix.ecs_task_definition_family }}
          ECS_SERVICE: ${{ matrix.ecs_service }}
          ECS_CLUSTER: ${{ matrix.ecs_cluster }}