name: Provision

on:
  workflow_dispatch:

jobs:
  parse-environment:
    uses: ./.github/workflows/parse_environment.yml

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: ./.github/workflows/setup_environment.sh
        shell: bash

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        env:
          TF_INPUT: 0
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: terraform apply -auto-approve
        working-directory: ./terraform
